// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1JB7TRZ657plZFwK0EwW_zFirHEvGwA',
    appId: '1:462418062845:web:a391ea62c834524f32bd94',
    messagingSenderId: '462418062845',
    projectId: 'kecconnect-76d99',
    authDomain: 'kecconnect-76d99.firebaseapp.com',
    storageBucket: 'kecconnect-76d99.appspot.com',
    measurementId: 'G-KP2DSFSSFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIAMiKCIBUYZo13wBBPpbsMSQMHojVXao',
    appId: '1:462418062845:android:a1a42fe36369444f32bd94',
    messagingSenderId: '462418062845',
    projectId: 'kecconnect-76d99',
    storageBucket: 'kecconnect-76d99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRL48lbHbl5wNbfAiXUeZ3eiUzZqCRAgU',
    appId: '1:462418062845:ios:826e6c5b19c9130332bd94',
    messagingSenderId: '462418062845',
    projectId: 'kecconnect-76d99',
    storageBucket: 'kecconnect-76d99.appspot.com',
    iosBundleId: 'com.example.kecconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRL48lbHbl5wNbfAiXUeZ3eiUzZqCRAgU',
    appId: '1:462418062845:ios:4b441ce0cfc682a732bd94',
    messagingSenderId: '462418062845',
    projectId: 'kecconnect-76d99',
    storageBucket: 'kecconnect-76d99.appspot.com',
    iosBundleId: 'com.example.kecconnect.RunnerTests',
  );
}
